[Interface]
PrivateKey = <Server_Private_Key>
Address = 10.0.0.1/32
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o <Interface> -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o <Interface> -j MASQUERADE

[Peer]
PublicKey = <Client_Public_Key>
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = <Client_Public_Key>
AllowedIPs = 10.0.0.3/32